$paths = @(
    "c:\Users\USER\Documents\SistemaDeDenuncias\SD\database\init.sql",
    "c:\Users\USER\Documents\SistemaDeDenuncias\SD\database\README.md"
)

foreach ($path in $paths) {
    if (Test-Path $path) {
        Write-Host "Fixing $path..."
        $txt = [System.IO.File]::ReadAllText($path)
        
        # Explicit replacements avoiding special char issues in script source
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0xA1, "á")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0xA9, "é")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0xAD, "í")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0xB3, "ó")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0xFA, "ú")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0xB1, "ñ")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0x91, "Ñ")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0x93, "Ó")
        $txt = $txt.Replace([String][char]0xC3 + [String][char]0x89, "É")
        
        # Also try "Ã" + char style if the file was saved as ANSI/ISO locally
        # Ã = 0xC3 in Latin1? No, Ã is 0xC3 in UTF8 but 0xC3 is Ã in Latin1.
        # Ideally we just look for the literal sequence generated by reading UTF8 bytes as Latin1.
        
        $txt = $txt.Replace("Ã¡", "á")
        $txt = $txt.Replace("Ã©", "é")
        $txt = $txt.Replace("Ã" + [char]0xAD, "í") # Soft hyphen
        $txt = $txt.Replace("Ã³", "ó")
        $txt = $txt.Replace("Ãº", "ú")
        $txt = $txt.Replace("Ã±", "ñ")
        $txt = $txt.Replace("Ã‘", "Ñ")
        $txt = $txt.Replace("Ã“", "Ó")
        
        [System.IO.File]::WriteAllText($path, $txt)
    }
}
Write-Host "Done."
